TRACKED_JOB_SOURCE_SEARCH_RESULT = "search_result"
TRACKED_JOB_SOURCE_MANUAL = "manual"
TRACKED_JOB_SOURCES = (
    TRACKED_JOB_SOURCE_SEARCH_RESULT,
    TRACKED_JOB_SOURCE_MANUAL,
)

TRACKED_JOB_STATUS_SAVED = "saved"
TRACKED_JOB_STATUS_TO_APPLY = "to_apply"
TRACKED_JOB_STATUS_APPLIED = "applied"
TRACKED_JOB_STATUS_SCREENING = "screening"
TRACKED_JOB_STATUS_INTERVIEW = "interview"
TRACKED_JOB_STATUS_TAKE_HOME = "take_home"
TRACKED_JOB_STATUS_FINAL_ROUND = "final_round"
TRACKED_JOB_STATUS_OFFER = "offer"
TRACKED_JOB_STATUS_REJECTED = "rejected"
TRACKED_JOB_STATUS_WITHDRAWN = "withdrawn"
TRACKED_JOB_STATUS_ARCHIVED = "archived"
TRACKED_JOB_STATUSES = (
    TRACKED_JOB_STATUS_SAVED,
    TRACKED_JOB_STATUS_TO_APPLY,
    TRACKED_JOB_STATUS_APPLIED,
    TRACKED_JOB_STATUS_SCREENING,
    TRACKED_JOB_STATUS_INTERVIEW,
    TRACKED_JOB_STATUS_TAKE_HOME,
    TRACKED_JOB_STATUS_FINAL_ROUND,
    TRACKED_JOB_STATUS_OFFER,
    TRACKED_JOB_STATUS_REJECTED,
    TRACKED_JOB_STATUS_WITHDRAWN,
    TRACKED_JOB_STATUS_ARCHIVED,
)

TRACKED_JOB_STATUS_INTERVIEW_STAGES = (
    TRACKED_JOB_STATUS_INTERVIEW,
    TRACKED_JOB_STATUS_TAKE_HOME,
    TRACKED_JOB_STATUS_FINAL_ROUND,
    TRACKED_JOB_STATUS_OFFER,
)

TRACKED_JOB_STATUS_APPLIED_AND_BEYOND = (
    TRACKED_JOB_STATUS_APPLIED,
    TRACKED_JOB_STATUS_SCREENING,
    TRACKED_JOB_STATUS_INTERVIEW,
    TRACKED_JOB_STATUS_TAKE_HOME,
    TRACKED_JOB_STATUS_FINAL_ROUND,
    TRACKED_JOB_STATUS_OFFER,
    TRACKED_JOB_STATUS_REJECTED,
    TRACKED_JOB_STATUS_WITHDRAWN,
)

TRACKED_JOB_PRIORITY_LOW = "low"
TRACKED_JOB_PRIORITY_MEDIUM = "medium"
TRACKED_JOB_PRIORITY_HIGH = "high"
TRACKED_JOB_PRIORITIES = (
    TRACKED_JOB_PRIORITY_LOW,
    TRACKED_JOB_PRIORITY_MEDIUM,
    TRACKED_JOB_PRIORITY_HIGH,
)

TRACKED_JOB_ACTIVITY_NOTE = "note"
TRACKED_JOB_ACTIVITY_STATUS_CHANGE = "status_change"
TRACKED_JOB_ACTIVITY_FOLLOW_UP = "follow_up"
TRACKED_JOB_ACTIVITY_INTERVIEW = "interview"
TRACKED_JOB_ACTIVITY_TYPES = (
    TRACKED_JOB_ACTIVITY_NOTE,
    TRACKED_JOB_ACTIVITY_STATUS_CHANGE,
    TRACKED_JOB_ACTIVITY_FOLLOW_UP,
    TRACKED_JOB_ACTIVITY_INTERVIEW,
)

TRACKED_JOB_CONTACT_RELATION_RECRUITER = "recruiter"
TRACKED_JOB_CONTACT_RELATION_HIRING_MANAGER = "hiring_manager"
TRACKED_JOB_CONTACT_RELATION_REFERRAL = "referral"
TRACKED_JOB_CONTACT_RELATION_INTERVIEWER = "interviewer"
TRACKED_JOB_CONTACT_RELATION_OTHER = "other"
TRACKED_JOB_CONTACT_RELATIONS = (
    TRACKED_JOB_CONTACT_RELATION_RECRUITER,
    TRACKED_JOB_CONTACT_RELATION_HIRING_MANAGER,
    TRACKED_JOB_CONTACT_RELATION_REFERRAL,
    TRACKED_JOB_CONTACT_RELATION_INTERVIEWER,
    TRACKED_JOB_CONTACT_RELATION_OTHER,
)

TRACKED_JOB_INTERVIEW_FORMAT_PHONE = "phone"
TRACKED_JOB_INTERVIEW_FORMAT_ZOOM = "zoom"
TRACKED_JOB_INTERVIEW_FORMAT_ONSITE = "onsite"
TRACKED_JOB_INTERVIEW_FORMAT_ASYNC = "async"
TRACKED_JOB_INTERVIEW_FORMATS = (
    TRACKED_JOB_INTERVIEW_FORMAT_PHONE,
    TRACKED_JOB_INTERVIEW_FORMAT_ZOOM,
    TRACKED_JOB_INTERVIEW_FORMAT_ONSITE,
    TRACKED_JOB_INTERVIEW_FORMAT_ASYNC,
)

TRACKED_JOB_SORT_UPDATED_AT = "updated_at"
TRACKED_JOB_SORT_DEADLINE_AT = "deadline_at"
TRACKED_JOB_SORT_NEXT_FOLLOW_UP_AT = "next_follow_up_at"
TRACKED_JOB_SORT_APPLIED_AT = "applied_at"
TRACKED_JOB_SORT_OPTIONS = (
    TRACKED_JOB_SORT_UPDATED_AT,
    TRACKED_JOB_SORT_DEADLINE_AT,
    TRACKED_JOB_SORT_NEXT_FOLLOW_UP_AT,
    TRACKED_JOB_SORT_APPLIED_AT,
)
